### PR TITLE
Fixes multiple links in 1 chat message.

### LINKED ISSUE #9362: Goon chat links don't end when the link stops
#### Description of issue

Since Goon chat, links don't properly end when the link ought to end:

Seemingly, the bug only happens with multiple links, may have a different effect in deadchat vs. OOC, and may have a different effect if separated by a period.
#### Difference between expected and actual behavior

Expected proper links, got one big link consisting of two links and all plain text in-between.
#### Steps to reproduce

Link two things (or one thing twice) in a single message in any chat.
#### Length of time in which bug has been known to occur

Since Goon chat got merged.
#### Server revision

02e5457c3d459b11fb5a01db5622cae3b0a2a1be
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) and the only issue related to links I could find was #9353

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes #9362

### CODE REVIEW

File: goon/browserassets/js/browserOutput.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ if (typeof String.prototype.trim !== 'function') {
 
 //Shit fucking piece of crap that doesn't work god fuckin damn it
```
Comment (ghost) [inline goon/browserassets/js/browserOutput.js:87]: Petition to run a script which appends this to the start of every .DM file in our codebase.

**Comment by Probe1** [comment]
tested, werks, mergewhen
