### PR TITLE
Fixes goonchat highlighting. Again.

### LINKED ISSUE #11115: Highlight string function is displaying the span tags in text
#### Description of issue

image
#### Difference between expected and actual behavior

I should be seeing those things with tags as highlighted
#### Steps to reproduce

Set your chat to highlight the words "AI," "door," "borg," "law," and "open," to make up for your horrible attention span
Play silicon
Go insane
#### Specific information for locating

I dunno, seems to happen for any word I've tried
#### Length of time in which bug has been known to occur

Didn't happen at all this morning(4AM-ish), started happening now. Supposedly for other people this has always happened? ("Yeah that's still broken")
#### Server revision

1be8cec8a3bca7e1c9a02f952e4af8f1b80e127a 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### PR DESCRIPTION
**Pull request by PJB3005**
Fixes  #11115

### CODE REVIEW

File: goon/browserassets/js/browserOutput.js [hunk 1]
```diff
@@ -113,7 +113,18 @@ function highlightTerms(el) {
 			highlightTerms(el.children[h]);
 		}
 	}
-	if (el.childNodes.length > 0 && typeof el.childNodes[0].data !== 'undefined' && el.childNodes[0].data.length > 0) { //If element actually has text
+
+	var hasTextNode = false;
+	for (var node = 0; node < el.childNodes.length; node++)
```
Comment (ComicIronic) [inline goon/browserassets/js/browserOutput.js:118]: Why are you doing this here when the identical loop is repeated below?

File: goon/browserassets/js/browserOutput.js [hunk 2]
```diff
@@ -122,11 +133,11 @@ function highlightTerms(el) {
 					var newWord = null;
 					for (var i = 0; i < opts.highlightTerms.length; i++) { //Each highlight term
 						if (opts.highlightTerms[i] && words[w].toLowerCase().indexOf(opts.highlightTerms[i].toLowerCase()) > -1) { //If a match is found
-							newWord = words[w].replace(new RegExp(opts.highlightTerms[i], 'gi'), addHighlightMarkup);
+							newWord = words[w].replace("<", "&lt;").replace(new RegExp(opts.highlightTerms[i], 'gi'), addHighlightMarkup);
 							break;
 						}
 					}
-					newText += (newWord ? newWord : words[w]).replace("<", "&lt;");
+					newText += newWord || words[w];
```
Comment (ComicIronic) [inline goon/browserassets/js/browserOutput.js:140]: Does this even work in js?

Comment (PJB3005) [inline goon/browserassets/js/browserOutput.js:140]: Yes.

File: goon/browserassets/js/browserOutput.js (hunk 1 above)
Comment (PJB3005) [inline goon/browserassets/js/browserOutput.js:118]: Performance reasons.

If we have text nodes the below needs to be done, but if we don't it'd be wasteful to do so.

File: goon/browserassets/js/browserOutput.js (hunk 2 above)
Comment (PJB3005) [inline goon/browserassets/js/browserOutput.js:140]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators

> Returns expr1 if it can be converted to true; otherwise, returns expr2. Thus, when used with Boolean values, || returns true if either operand can be converted to true; if both can be converted to false, returns false.

**Comment by clusterfack** [comment]
Oh I thought you said it was impossible, well either way good job
